// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJETDOTNETQ5.Data;

#nullable disable

namespace PROJETDOTNETQ5.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240104184554_AddExtraterrestrialRelation")]
    partial class AddExtraterrestrialRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CelestialObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestMomentsAndSpots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Mesh")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Obj")
                        .HasColumnType("float");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTime>("PositionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CelestialObjects");
                });

            modelBuilder.Entity("PROJETDOTNETQ5.Models.Extraterrestrial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestMomentsAndSpots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CelestialObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CelestialObjectId")
                        .IsUnique();

                    b.ToTable("Extraterrestrials");
                });

            modelBuilder.Entity("PROJETDOTNETQ5.Models.Extraterrestrial", b =>
                {
                    b.HasOne("CelestialObject", "CelestialObject")
                        .WithOne("ExtraterrestrialObject")
                        .HasForeignKey("PROJETDOTNETQ5.Models.Extraterrestrial", "CelestialObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CelestialObject");
                });

            modelBuilder.Entity("CelestialObject", b =>
                {
                    b.Navigation("ExtraterrestrialObject")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
